config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :employees
  resources :documents
  # custom_routes
  get 'about' => "pages#about_us"
  get 'contact'=> "pages#contact_us"
  get 'privacy-policy' => "pages#privacy_policy"
  get "terms-and-conditions" => "pages#terms_and_conditions"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  DOC_TYPES = ["Educational", "salary", "photo-id", "proofs", "others"].freeze
  belongs_to :employee
  has_one_attached :file
  validates :name, :doc_type, :employee_id, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :documents
	validates :first_name, :last_name, presence: true
	validates :personal_email, uniqueness: true, presence: true
	validates :city, :state, :country, :pincode, :address_line_1, presence: true

	def name
		"#{first_name} #{last_name}".strip
	end

	def full_address
		"#{address_line_1} #{address_line_2}, #{city}, #{state}, #{country}, #{pincode}".strip
	end

	def name_with_email
		"#{name} (#{personal_email})" 
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable , :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :set_document, only: [:edit, :show, :update, :destroy]

	def index
		@documents = Document.all
	end

	def new
		@document = Document.new
	end

	def create
		@document = Document.new(document_params)
		if @document.save
			redirect_to documents_path, notice: "Document created successfully"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @document.update(document_params)
			redirect_to documents_path, notice: "Document updated successfully"
		else
			render :edit
		end
	end

	def show
	end

	def destroy
		if @document.destroy
			redirect_to documents_path, notice: "Document deleted successfully"
		else
			flash[:errors] = "Something went wrong!"
			redirect_to documents_path
		end
	end

	private

	def set_document
		@document = Document.find(params[:id])
	rescue ActiveRecord::RecordNotFound => error
		redirect_to documents_path, notice: "Document not found"
	end


	def document_params
		params.require(:document).permit(:name, :doc_type, :employee_id, :file)
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :set_employee, only:[:edit, :show, :update, :delete]
	def index
		@employees = Employee.all
	end

	def new
		@employee = Employee.new
	end

	def create
		@employee = Employee.new(employee_params)
		if @employee.save
			redirect_to employees_path, notice: "Employee Created Successfully"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @employee.update(employee_params)
			redirect_to employees_path, notice: "Employee Updated Successfully"
		else
			render :edit
		end
	end

	def show
	end

	def destroy
		if @employee.destroy
			redirect_to employees_path, notice: "Employee Deleted Successfully"
		else
			flash[:errors] = "Something went wrong!"
		end
	end


	private

	def set_employee
		@employee = Employee.find(params[:id])
	#rescue ActiveRecord :: RecordNotFound => error
		#redirect_to employees_path, notice: error
	end

	def employee_params
		params.require(:employee).permit(:first_name, :last_name, :personal_email, :city, :state, :country, :pincode, :address_line_1, :address_line_2)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@title_text = "Hello World"
		@subtitle_text = "Welcome to Ruby on Rails"
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_form.html.erb
<!-- app/views/documents/_form.html.erb -->
<%= form_for @document, html: { multipart: true } do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h4>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :doc_type, class: "form-label" %>
    <%= f.text_field :doc_type, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :employee_id, class: "form-label" %>
    <%= f.select :employee_id, options_for_select(Employee.all.map { |employee| [employee.name, employee.id] }), { prompt: 'Select an Employee' }, { class: 'form-select' } %>
  </div>

  <div class="mb-3">
    <%= f.label :file, class: "form-label" %>
    <%= f.file_field :file, class: "form-control" %>
  </div>

  <div class="text-center">
    <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
    <%= link_to "Cancel", documents_path, class: "btn btn-secondary btn-lg ms-2" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<!-- app/views/documents/edit.html.erb -->
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <h2 class="card-title text-center">Edit Document</h2>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/documents/index.html.erb
<!-- app/views/documents/index.html.erb -->
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <%= flash[:notice] %>
      <div class="card border-0 shadow-sm mt-5 mb-5">
        <div class="card-body">
          <h2 class="card-title text-center">Listing All Documents</h2>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Employee Name</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @documents.each do |document| %>
              <tr>
                <td><%= document.name %></td>
                <td><%= document.doc_type %></td>
                <td><%= link_to document.employee.name, employee_path(document.employee) %></td>
                <td class="mt-2">
                  <%= link_to "Show", document_path(document), class: "btn btn-primary btn-sm" %>
                  <%= link_to "Edit", edit_document_path(document), class: "btn btn-secondary btn-sm" %>
                  <%= link_to "Delete", document_path(document), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", remote: true %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to "New Document", new_document_path, class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/documents/new.html.erb
<!-- app/views/documents/new.html.erb -->
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <h2 class="card-title text-center mb-4">New Document</h2>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/documents/show.html.erb
<!-- app/views/documents/show.html.erb -->
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <h2 class="card-title text-center"><%= @document.name %></h2>
          <p class="card-text"><strong>Type:</strong> <%= @document.doc_type %></p>
          <p class="card-text"><strong>Employee ID:</strong> <%= @document.employee_id %></p>
          <% if @document.file.attached? %>
            <%= image_tag @document.file.variant(resize_to_fit: [400, 400]) %>
          <% end %>
          <div class="text-center mt-3">
            <%= link_to "Edit", edit_document_path(@document), class: "btn btn-primary" %>
            <%= link_to "Back to Documents", documents_path, class: "btn btn-secondary ms-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <h2 class="text-center mb-4">Edit Employee</h2>
          <%= form_with(model: @employee, html: { class: "row g-3" }) do |form| %>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :first_name, class: "form-control rounded-0", id: "first_name", placeholder: " " %>
                <%= form.label :first_name, "First Name", class: "form-label" %>
              </div>
              <% if @employee.errors[:first_name].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:first_name).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :last_name, class: "form-control rounded-0", id: "last_name", placeholder: " " %>
                <%= form.label :last_name, "Last Name", class: "form-label" %>
              </div>
              <% if @employee.errors[:last_name].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:last_name).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-12">
              <div class="form-floating">
                <%= form.email_field :personal_email, class: "form-control rounded-0", id: "personal_email", placeholder: " " %>
                <%= form.label :personal_email, "Personal Email", class: "form-label" %>
              </div>
              <% if @employee.errors[:personal_email].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:personal_email).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :address_line_1, class: "form-control rounded-0", id: "address_line_1", placeholder: " " %>
                <%= form.label :address_line_1, "Address Line 1", class: "form-label" %>
              </div>
              <% if @employee.errors[:address_line_1].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:address_line_1).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :address_line_2, class: "form-control rounded-0", id: "address_line_2", placeholder: " " %>
                <%= form.label :address_line_2, "Address Line 2", class: "form-label" %>
              </div>
              <% if @employee.errors[:address_line_2].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:address_line_2).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-4">
              <div class="form-floating">
                <%= form.text_field :city, class: "form-control rounded-0", id: "city", placeholder: " " %>
                <%= form.label :city, "City", class: "form-label" %>
              </div>
              <% if @employee.errors[:city].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:city).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-4">
              <div class="form-floating">
                <%= form.text_field :state, class: "form-control rounded-0", id: "state", placeholder: " " %>
                <%= form.label :state, "State", class: "form-label" %>
              </div>
              <% if @employee.errors[:state].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:state).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-4">
              <div class="form-floating">
                <%= form.text_field :country, class: "form-control rounded-0", id: "country", placeholder: " " %>
                <%= form.label :country, "Country", class: "form-label" %>
              </div>
              <% if @employee.errors[:country].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:country).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-3">
              <div class="form-floating">
                <%= form.text_field :pincode, class: "form-control rounded-0", id: "pincode", placeholder: " " %>
                <%= form.label :pincode, "Pincode", class: "form-label" %>
              </div>
              <% if @employee.errors[:pincode].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:pincode).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-12 mt-4">
              <%= form.submit "Submit", class: "btn btn-primary rounded-0" %>
              <%= link_to 'Cancel', employees_path, class: "btn btn-secondary rounded-0 ms-2" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-12">
      <%= flash[:notice] %>
      <div class="card border-0 shadow-sm mt-5 mb-5">
        <div class="card-body">
          <h2 class="text-center">Listing All Employees</h2>
        </div>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Personal Email</th>
            <th>Address</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
          <tr>
            <td><%= employee.name %></td>
            <td><%= employee.personal_email %></td>
            <td><%= employee.full_address %></td>
            <td class="mt-2">
              <div class="dropdown">
                <button class="btn btn-secondary btn-sm dropdown-toggle rounded-0 me-2" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                  Actions
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li><%= link_to "Show", employee_path(employee), class: "dropdown-item" %></li>
                  <li><%= link_to "Edit", edit_employee_path(employee), class: "dropdown-item" %></li>
                  <li><%= link_to "Delete", employee_path(employee), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "dropdown-item text-danger", remote: true %></li>
                </ul>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "New Employee", new_employee_path, class: "btn btn-primary btn-lg rounded-0" %>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <h2 class="text-center mb-4">Create New Employee</h2>
          <%= form_with model: @employee, html: { class: "row g-3" } do |form| %>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :first_name, class: "form-control rounded-0", id: "first_name", placeholder: " " %>
                <%= form.label :first_name, "First Name", class: "form-label" %>
              </div>
              <% if @employee.errors[:first_name].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:first_name).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :last_name, class: "form-control rounded-0", id: "last_name", placeholder: " " %>
                <%= form.label :last_name, "Last Name", class: "form-label" %>
              </div>
              <% if @employee.errors[:last_name].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:last_name).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-12">
              <div class="form-floating">
                <%= form.email_field :personal_email, class: "form-control rounded-0", id: "personal_email", placeholder: " " %>
                <%= form.label :personal_email, "Personal Email", class: "form-label" %>
              </div>
              <% if @employee.errors[:personal_email].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:personal_email).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :address_line_1, class: "form-control rounded-0", id: "address_line_1", placeholder: " " %>
                <%= form.label :address_line_1, "Address Line 1", class: "form-label" %>
              </div>
              <% if @employee.errors[:address_line_1].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:address_line_1).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                <%= form.text_field :address_line_2, class: "form-control rounded-0", id: "address_line_2", placeholder: " " %>
                <%= form.label :address_line_2, "Address Line 2", class: "form-label" %>
              </div>
              <% if @employee.errors[:address_line_2].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:address_line_2).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-4">
              <div class="form-floating">
                <%= form.text_field :city, class: "form-control rounded-0", id: "city", placeholder: " " %>
                <%= form.label :city, "City", class: "form-label" %>
              </div>
              <% if @employee.errors[:city].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:city).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-4">
              <div class="form-floating">
                <%= form.text_field :state, class: "form-control rounded-0", id: "state", placeholder: " " %>
                <%= form.label :state, "State", class: "form-label" %>
              </div>
              <% if @employee.errors[:state].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:state).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-4">
              <div class="form-floating">
                <%= form.text_field :country, class: "form-control rounded-0", id: "country", placeholder: " " %>
                <%= form.label :country, "Country", class: "form-label" %>
              </div>
              <% if @employee.errors[:country].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:country).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-md-3">
              <div class="form-floating">
                <%= form.text_field :pincode, class: "form-control rounded-0", id: "pincode", placeholder: " " %>
                <%= form.label :pincode, "Pincode", class: "form-label" %>
              </div>
              <% if @employee.errors[:pincode].any? %>
                <div class="text-danger"><%= @employee.errors.full_messages_for(:pincode).join(', ') %></div>
              <% end %>
            </div>
            <div class="col-12 mt-4">
              <%= form.submit "Submit", class: "btn btn-primary rounded-0" %>
              <%= link_to 'Back to Employee', employees_path, class: "btn btn-secondary rounded-0 ms-2" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <h2 class="text-center mb-4">Employee Details</h2>
          <dl class="row">
            <dt class="col-sm-3">Name:</dt>
            <dd class="col-sm-9"><%= @employee.name %></dd>

            <dt class="col-sm-3">Personal Email:</dt>
            <dd class="col-sm-9"><%= @employee.personal_email %></dd>

            <dt class="col-sm-3">Address:</dt>
            <dd class="col-sm-9"><%= @employee.full_address %></dd>
          </dl>

          <h3 class="mb-3">Employee Documents:</h3>
          <% if @employee.documents.present? %>
          <% @employee.documents.each do |document| %>
            <div class="card mb-4">
              <div class="card-body">
                <% if document.file.attached? %>
                  <%= image_tag document.file.variant(resize_to_fit: [200, 200]) %>
                <% end %>
              </div>
              <div class="card-body">
                <%= document.name %>
              </div>
              <div class="card-body">
                <%= document.doc_type %>
              </div>
            </div>
          <% end %>
          <% end %>

          <div class="text-center">
            <%= link_to 'Edit', edit_employee_path(@employee), class: "btn btn-secondary rounded-0 me-2" %>
            <%= link_to "Delete", employee_path(@employee), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm rounded-0" %>
          </div>
          <%= link_to 'Back to Employees', employees_path, class: "btn btn-primary btn-lg rounded-0 mt-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HrMitra</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render 'shared/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <div class="row">
      <%= yield %>
  <%= render 'shared/footer' %> 
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
	<h1 class="text-center">About HR Mitra</h1>
	<%= render 'shared/dummy-content' %>
</div>
<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<%= render 'shared/links' %>
<div class="col-lg-10 mx-auto">
	<h1 class="text-center">Contact HR Mitra</h1>
	<%= render 'shared/dummy-content' %>
</div>

app/views/pages/privacy_policy.html.erb
<%= render 'shared/links' %>
<div class="col-lg-10 mx-auto">
	<h1 class="text-center">About HR Privacy and Policy</h1>
	<%= render 'shared/dummy-content' %>
</div>

app/views/pages/terms_and_conditions.html.erb
<%= render 'shared/links' %>
<div class="col-lg-10 mx-auto">
	<h1 class="text-center">HR Mitra Terms and Conditions</h1>
	<%= render 'shared/dummy-content' %>
</div>

app/views/shared/_dummy-content.html.erb
<p class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

	<p class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

	<p class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

	<p class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

app/views/shared/_footer.html.erb
<footer class="bd-footer py-4 py-md-5 mt-5 bg-secondary" style="width: 100%; position: fixed; bottom: 0; left: 0;">
  <div class="container py-4 py-md-5 px-4 px-md-3 text-body-secondary">
    <div class="row">
      <div class="col-lg-12 mb-3">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <title>HR Mitra</title>
        <span class="fs-5">
          <i class="fas fa-h-square"></i> HR Mitra
        </span>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
    <%= link_to "Hr Mitra", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<div class="container" style="background-image: url('https://www.freecodecamp.org/news/content/images/size/w2000/2021/06/w-qjCHPZbeXCQ-unsplash.jpg'); background-size: cover; background-position: center; padding: 50px; height: 100vh;">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <h1 class="text-center">Hr Mitra</h1>

      <div class="text-center">
        <%= link_to "About Us", about_path, target: '_blank', data: {name: 'about_page', resource: 'pages'}, class: 'btn btn-success btn-lg', style: 'margin-right: 10px;' %>
      </div>

      <br>

      <div class="text-center">
        <%= link_to "Contact Us", contact_path, target: '_blank', class: 'btn btn-secondary btn-lg', style: 'margin-right: 10px;' %>
        <%= link_to "Privacy Policy", privacy_policy_path, target: '_blank', class: 'btn btn-secondary btn-lg', style: 'margin-right: 10px;' %>
        <%= link_to "Terms and Conditions", terms_and_conditions_path, target: '_blank', class: 'btn btn-secondary btn-lg', style: 'margin-right: 10px;' %>
      </div>

      <br>

      <div class="text-center">
        <%= link_to "List of Employees", employees_path, class: "btn btn-primary btn-lg", style: 'margin-right: 10px;' %>
        <%= link_to "List of Documents", documents_path, class: "btn btn-primary btn-lg", style: 'margin-right: 10px;' %>
      </div>

      <br>

      <div class="text-center">
        <% if user_signed_in? %>
          <%= link_to 'Sign_out', destroy_user_session_path, method: :delete, data: {confirm: "Your current session will be destroyed Are you sure to logout"}, class: "btn btn-danger btn-lg", style: 'margin-right: 10px;'  %>
        <% end %>
      </div>
    </div>
  </div>
</div>